version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: monthly

    # Group all package updates into one PR
    groups:
      main:
        patterns:
          - "*"