# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Update hooks with `pre-commit autoupdate`
# Manually run with `pre-commit run --all-files`
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
      - id: check-case-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Scan the latest commit for any secrets
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail --no-update'
        language: system
        stages: ["commit", "push"]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.376
    hooks:
      - id: pyright
