services:
  transcription-bot:
    container_name: transcription-bot
    build:
      dockerfile: ./Dockerfile
      target: deployment
    restart: always
    volumes:
      - ./credentials:/app/credentials
    env_file:
      - path: env/prod.env
        required: true
