services:
  transcription-bot:
    container_name: transcription-bot
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
      # The container will appear to 'hang' initially as it downloads model files.
      - .cache:/home/vscode/.cache # Cache models
    # Why do I have to install requirements separately, and then install this project
    command: pip install -e .python3 /app/src/bot.py
    env_file:
      - path: .env
        required: false # Github actions uses secrets directly