services:
  transcription-bot:
    container_name: transcription-bot
    build: .
    restart: unless-stopped
    volumes: 
      - .:/app
      # The container will appear to 'hang' initially as it downloads model files.
      - .cache:/home/vscode/.cache # Cache models
    command: python3 /app/src/bot.py