services:
  transcription-bot:
    container_name: transcription-bot
    user: 1000:1000
    build: .
    restart: unless-stopped
    volumes: 
      - .:/app
      - .cache:/home/vscode/.cache # Cache models
    command: python3 /app/bot.py