name: Build and Test on PR
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Allow multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Options: https://github.com/docker/build-push-action
      # Note: uses the Git reference as context, so file mutations prior are ignored
      - name: Build the `test` target
        uses: docker/build-push-action@v6
        with:
          push: false
          target: test
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
