name: Run pytest
on: pull_request

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Set up pdm
              run: |
                python -m pip install --upgrade pip
                pip install pdm

            - name: Test
              run: |
                pdm run test