name: Update pdm dependencies, test & commit
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Set up pdm
        run: |
          curl -sSL https://pdm-project.org/install-pdm.py | python3 -

      - name: Update dependencies
        run: pdm update -u

      - name: Check if files changed
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Run tests
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pdm run test
        timeout-minutes: 60
        env:
          MY_USERNAME: ${{ secrets.MY_USERNAME }}
          API_HASH: ${{ secrets.API_HASH }}
          API_ID: ${{ secrets.API_ID }}

      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update dependencies"
